AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Parameters:
  AlexaSQSQueueARN: 
    Type: String
    Default: ''
    Description: 'AlexaSQSQueueARN'
Resources:
  SmartTVVoiceControl:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: SmartTVVoiceControl
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: source
      Description: ''
      MemorySize: 128
      Timeout: 3
      Policies:
        - Statement:
          - Sid: SQSPolicy
            Effect: Allow
            Action: 
              - sqs:GetQueueUrl
              - sqs:ChangeMessageVisibility
              - sqs:ChangeMessageVisibilityBatch
              - sqs:DeleteMessage
              - sqs:DeleteMessageBatch
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
              - sqs:SendMessage
            Resource: !Ref AlexaSQSQueueARN
      Environment:
        Variables:
          SQS_QUEUE_ARN: !Ref AlexaSQSQueueARN
